In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import keras
%matplotlib inline

In [2]:
#importing dataset 
df= pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df.shape

(28, 3)

In [4]:
# splitting dataset into training and testing data
x= df[['age','affordibility']]
y= df.bought_insurance

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=101)

In [5]:
# Feature scaling
x_train_scaled= x_train.copy()
x_train_scaled['age']= x_train_scaled['age']/100

x_test_scaled= x_test.copy()
x_test_scaled['age']= x_test_scaled['age']/100

x_train_scaled.head()

age  affordibility
21  0.26              0
22  0.40              1
10  0.18              1
20  0.21              1
3   0.52              0

In [ ]:
model = keras.Sequential([
        keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
                           ])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_scaled,y_train,epochs=5000)

Epoch 1/5000


C:\Users\vaibh\Downloads\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.4091 - loss: 0.8017
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.4091 - loss: 0.8011
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4091 - loss: 0.8006
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4091 - loss: 0.8000
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.4091 - loss: 0.7994
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.4091 - loss: 0.7988
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.4091 - loss: 0.7982
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.4091 - loss: 0.7976
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4091 - loss: 0.7970
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.4091 - loss: 0.7964
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.4091 - loss: 0.7959
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.4091 - loss

In [9]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 816ms/step - accuracy: 0.6667 - loss: 0.8338


[0.8337938785552979, 0.6666666865348816]

In [10]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step


array([[0.06943887],
       [0.6565728 ],
       [0.2894585 ],
       [0.08730839],
       [0.6280509 ],
       [0.69288707]], dtype=float32)

In [11]:
coeff, weight= model.get_weights()
coeff,weight

(array([[4.1398177],
        [1.9600558]], dtype=float32),
 array([-3.381906], dtype=float32))